---
- name: Apache installation for ubuntuservers
  hosts: ubuntuservers
  tasks:
   - name: installing apache
     apt:
       name: apache2
       state: present

   - name: index.html
     copy:
       content: "<h1>Hello Najwa Alshahrani</h1>"
       dest: /var/www/html/index.html

   - name: restart apache2
     service:
       name: apache2
       state: restarted
       enabled: yes

- name: Apache wget installation for AmzLinuxservers
  hosts: AmzLinuxservers
  tasks:
    - name: installing httpd and wget
      yum:
       pkg: ['httpd', 'wget']
       state: present

   - name: index.html
     copy:
       content: "<h1>Hello Najwa Alshahrani</h1>"
       dest: /var/www/html/index.html   
    